# Generated by Django 3.1.5 on 2021-03-21 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='time_to_die',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
