# Generated by Django 3.1.5 on 2021-03-12 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='mycinema.session', verbose_name='Сеанс')),
            ],
        ),
    ]
