# Generated by Django 3.1.5 on 2021-01-21 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20210121_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_like', to=settings.AUTH_USER_MODEL)),
                ('comment_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_dislike', to=settings.AUTH_USER_MODEL)),
                ('comment_dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_dislike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
