# Generated by Django 3.1.5 on 2021-01-21 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_dislike_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author_dislike', to=settings.AUTH_USER_MODEL)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_dislike', to='myapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author_like', to=settings.AUTH_USER_MODEL)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_like', to='myapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='CommentDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author_dislike', to=settings.AUTH_USER_MODEL)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_dislike', to='myapp.comment')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author_like', to=settings.AUTH_USER_MODEL)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='myapp.comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='article_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment_like',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
