# Generated by Django 3.1.5 on 2021-04-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myavio', '0007_likepost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('user', 'post')},
        ),
    ]
